@echo off
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /SU AUTO >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /SS %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /BS %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /BV %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /CS %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /PSN %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /PAT %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /PPN %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /IV %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /SM %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /SP %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /BS %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /SF %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /BM %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /BP %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /BT %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /BLC %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /CM %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /CT %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /CV %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /CA %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /CO %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /CSK %random%%random%%random%%random% >nul"
start cmd /c "C:\Windows\Fonts\AMIDEWINx64.EXE /SK %random%%random%%random%%random% >nul"
pause
